name = "Chill Pack 26 . 2 Mc"
author = "Grishkka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6ecd91fc0db4d6cfcd0ae417774985d0db90436e7bf766793636acb5b6e6e21"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
