name = "Chill Pack 26 . 2 Mc"
author = "Grishkka"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8797a0bb04622a622feb82740c414e7f6bbdafa8041984fdc226da6ecde5a6d"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
